### ISSUE TITLE
Standard Environment Variables Support

### ISSUE THREAD

**Issue by suntong** [padlocal/wechaty-puppet-padlocal-demo#5]
Please support the standard Environment Variables of

- `WECHATY_PUPPET`, see https://github.com/wechaty/wechaty-getting-started/blob/master/examples/ding-dong-bot.js
- and `WECHATY_PUPPET_HOSTIE_TOKEN`, see https://github.com/wechaty/wechaty-puppet-hostie

I had always been able to switch puppets by changing the above two Environment Variables with 
https://github.com/wechaty/wechaty-getting-started/blob/master/examples/ding-dong-bot.js

Hope wechaty-puppet-padlocal can be too someday. thx

**Comment by padlocal** [comment]
This feature has been supported officially.

Two ways to use wechaty-puppet-padlocal:
1. use wechaty-puppet-padlocal directly: https://github.com/wechaty/wechaty-getting-started#wechaty-puppets
2. use Wechaty Puppet Service: https://wechaty.js.org/2021/01/14/wechaty-puppet-service/
